version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - incident-sim-net

  user_service:
    build:
      context: ./services/user_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - incident-sim-net

networks:
  incident-sim-net:
    driver: bridge